# Generated by Django 6.0.8 on 2026-08-18 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('rent_per_month', models.DecimalField(decimal_places=2, help_text='Base / representative monthly rent for this PG.', max_digits=10, verbose_name='rent per month')),
                ('amenities', models.TextField(blank=True, help_text='Amenities offered by this PG (free-form text).', verbose_name='amenities')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this PG is currently listed and visible.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.ForeignKey(help_text='The owner who manages this PG property.', on_delete=django.db.models.deletion.CASCADE, related_name='pgs', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'PG',
                'verbose_name_plural': 'PGs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, verbose_name='room number')),
                ('room_type', models.CharField(blank=True, help_text='e.g. Single, Double, Dormitory', max_length=50, verbose_name='room type')),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of beds this room can hold.', verbose_name='capacity')),
                ('rent', models.DecimalField(decimal_places=2, help_text='Monthly rent for this room.', max_digits=10, verbose_name='rent')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this room is currently available for listing.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.pg', verbose_name='PG')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "Bed A", "Bed B"', max_length=50, verbose_name='label')),
                ('is_available', models.BooleanField(default=True, help_text='Inventory-level availability managed by the owner.', verbose_name='available')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bed is currently active in the system.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='properties.room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'Bed',
                'verbose_name_plural': 'Beds',
                'ordering': ['label'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('pg', 'room_number'), name='unique_room_number_per_pg'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('room', 'label'), name='unique_bed_label_per_room'),
        ),
    ]
