# Generated by Django 6.0.8 on 2026-09-17 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_bed_rent_per_month_and_schema_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Room photo (JPEG/PNG/WebP, max 3 per room).', upload_to='rooms/%Y/%m/', verbose_name='image')),
                ('caption', models.CharField(blank=True, help_text='Optional short caption for this photo.', max_length=120, verbose_name='caption')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order in which this image is displayed.', verbose_name='display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
