# Generated by Django 6.0.8 on 2026-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('OWNER', 'Owner'), ('ADMIN', 'Admin')], default='TENANT', help_text="Determines the user's platform permissions: Tenant, Owner, or Admin.", max_length=20, verbose_name='role'),
        ),
    ]
